name: pull_request
on: [pull_request]
jobs:
  pest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          extensions: gd
      - run: composer install
      - run: ./runTests.sh
